/**
 * Human-readable landing page for the MCP server.
 *
 * Most visitors will arrive via the JSON-RPC endpoint, but a plain GET to
 * the root should explain what this service is.
 */

export const metadata = {
  title: "OpenGIKAI MCP server",
};

export default function Page() {
  return (
    <main style={{ fontFamily: "system-ui, sans-serif", maxWidth: 720, margin: "3rem auto", padding: "0 1rem", lineHeight: 1.6 }}>
      <h1>OpenGIKAI MCP server</h1>
      <p>
        This service exposes OpenGIKAI&apos;s Japanese Diet transcript data as
        a read-only{" "}
        <a href="https://modelcontextprotocol.io">Model Context Protocol</a>{" "}
        server.
      </p>
      <h2>Endpoint</h2>
      <p>
        <code>POST /api/mcp</code> — JSON-RPC 2.0 over HTTP.
      </p>
      <h2>Discovery</h2>
      <p>
        <code>GET /api/mcp</code> returns the server info and the full tool
        list without a JSON-RPC roundtrip.
      </p>
      <h2>Available tools</h2>
      <ul>
        <li><code>search_threads</code> — query Diet discussion threads</li>
        <li><code>get_thread</code> — fetch a thread with full 3-level summaries</li>
        <li><code>get_member</code> — fetch a Diet member profile</li>
        <li><code>list_members</code> — paginate Diet members by name/party</li>
        <li><code>list_dates</code> — index of dates with available threads</li>
      </ul>
      <h2>Attribution</h2>
      <p>
        OpenGIKAI summaries are generated by Claude AI and are derivative
        works built on top of the National Diet Library&apos;s public-domain
        transcripts (Japanese Copyright Act, article 13). The underlying
        data and pipeline are open source:{" "}
        <a href="https://github.com/wharfe/open-gikai">github.com/wharfe/open-gikai</a>.
      </p>
    </main>
  );
}
